services:

  db:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
