CREATE DATABASE FOODLY;

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(15)
);

CREATE TABLE MENU (
    ID SERIAL PRIMARY KEY,
    IMAGE_SOURCE VARCHAR(200),
    TITLE VARCHAR(30),
    PRICE INTEGER,
    QUANTITY INTEGER,
    IS_AVAILABLE BOOLEAN DEFAULT TRUE,
    IS_ADVERTISED BOOLEAN DEFAULT FALSE,
    USER_ID INTEGER,
    CONSTRAINT user_fk FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);